# https://www.wormatlas.org/hermaphrodite/hypodermis/mainframe.htm#Listofcells5
hypodermis = {
    # 1. Head (anterior to the excretory pore; all embryonic)
    'ABarappaapa': 'hyp 1 (V)',
    'ABalpaapppa': 'hyp 1 (DL)',
    'ABaraaapppp': 'hyp 1 (DR) ',
    'ABalpapaaap': 'hyp 2 (V)',
    'ABalpaapppp': 'hyp 2 (DL)',
    'ABplaapaaaa': 'hyp 3 (D1/2)',
    'ABpraapaaaa': 'hyp 3 (D1/2)',
    'ABarpapapa': 'hyp 4 (D)',
    'ABpraappaa': 'hyp 4 (V1/2)',
    'ABplaappaa': 'hyp 4 (V1/2)',
    'ABplaaapp': 'hyp 5 (L)',
    'ABarpappap': 'hyp 5 (R)',
    'ABplaaaapa': 'hyp 6 (D1) ',
    'ABarpaapa': 'hyp 6 (D2)',
    'ABplaaaapp': 'hyp 6 (D3)',
    'ABarpapapp': 'hyp 6 (D4)',
    'ABplaappap': 'hyp 6 (V1/2)',
    'ABpraappap': 'hyp 6 (V1/2) ',
    'ABarpaapap': 'hyp 7 (D1)',
    'ABarpaappa': 'hyp 7 (D2) ',
    'ABpraapppa': 'hyp 7 (V18/19) ',
    'ABplaapppa': 'hyp 7 (V18/19)',

    # 2. Body (posterior to the excretory pore) Embryonic:

    'ABarpaappp': 'hyp 7(D3)',
    'ABarppaapa': 'hyp 7(D4)',
    'ABarpppapa': 'hyp 7(D5)',
    'Cpaaaa': 'hyp 7(D6)',
    'Caaaaa': 'hyp 7(D7)',
    'Cpaaap': 'hyp 7(D8)',
    'Caaaap': 'hyp 7(D9)',
    'Cpaapa': 'hyp 7(D10)',
    'Caaapa': 'hyp 7(D11)',
    'Cpaapp': 'hyp 7(D12)',
    'Caaapp': 'hyp 7(D13)',
    'Cpapaa': 'hyp 7(D14)',
    'Cpapap': 'hyp 7(D15)',
    'Cpappd': 'hyp 7(D16)',
    'Caappd': 'hyp 7(D17)',
    'ABplaapppp': 'hyp 7(V20)',
    'ABpraapppp': 'hyp 7(V21)',

    # 3. Tail (posterior to anus; all embryonic)
    'ABplappppa': 'hyp 7 (V22/23)',
    'ABprappppa': 'hyp 7 (V22/23)',
    'ABplpppapap': 'hyp 8/9',
    'ABprpppapap': 'hyp 8/9',
    'ABplppppppp': 'hyp 10 (V1/2)',
    'ABprppppppp': 'hyp 10 (V1/2)',
    'Cpappv': 'hyp 11',

}

atypical = {
    'XXXL': 'atypical',
    'XXXR': 'atypical',
    'ABplppppppa': 'atypical',
    'ABprppppppa': 'atypical',
}

# 体腔细胞
coelomocyte = ['MSapapaaa', 'MSppapaaa', 'MSapapaap', 'MSppapaap']

head_muscle = {
    'MSappaaa': 'hmc',
    'MSpppaaa': 'hmc homolog',
}

# Interfacial epithelial cells are located at the interface between the hypodermis and another type of tissue
interfacial = {
    'ABalpaappaa': 'arcade_interfacial',
    'ABaraaapppa': 'arcade_interfacial',
    'ABalpapaapa': 'arcade_interfacial',
    'ABalpaapaaa': 'arcade_interfacial',
    'ABaraaapaaa': 'arcade_interfacial',
    'ABarapapapa': 'arcade_interfacial',
    'ABalpaappap': 'arcade_interfacial',
    'ABaraaappap': 'arcade_interfacial',
    'ABaraaappaa': 'arcade_interfacial',

}

intestine = {
    'E*': 'intestine',
}

muscle_somatic = {
    'MSapappp': 'DL',
    'MSapaaap': 'DL',
    'MSappppa': 'DL',
    'MSapappa': 'DL',
    'MSappppp': 'DL',
    'MSapppap': 'DL',
    'Dappaa': 'DL',
    'Daaap': 'DL',
    'Dappap': 'DL',
    'Dapap': 'DL',
    'Dapppa': 'DL',
    'Cappaaa': 'DL',
    'Dapppp': 'DL',
    'Capapaa': 'DL',
    'Cappaap': 'DL',
    'Capapap': 'DL',
    'Capppaa': 'DL',
    'Cappapa': 'DL',
    'Capppap': 'DL',
    'Cappppd': 'DL',
    'Cappapp': 'DL',

    'MSapapap': 'VL',
    'MSappapp': 'VL',
    'MSapppaa': 'VL',
    'Daapa': 'VL',
    'Daapp': 'VL',
    'Daaaa': 'VL',
    'MSaapppaa': 'VL',
    'Dapaa': 'VL',
    'MSaapppap': 'VL',
    'Capaaaa': 'VL',
    'MSaappppa': 'VL',
    'Capaaap': 'VL',
    'MSaappppp': 'VL',
    'Capaapa': 'VL',
    'MSpappaa': 'VL',
    'Capaapp': 'VL',
    'Capappa': 'VL',
    'Capappp': 'VL',
    'Cappppv': 'VL',

    'MSpppapp': 'VR',
    'MSppapap': 'VR',
    'Dpapa': 'VR',
    'MSppppaa': 'VR',
    'Dpapp': 'VR',
    'Dpaaa': 'VR',
    'MSpapppap': 'VR',
    'Cppaaaa': 'VR',
    'MSpappppa': 'VR',
    'Cppaaap': 'VR',
    'MSpappppp': 'VR',
    'Cppaapa': 'VR',
    'MSpappap': 'VR',
    'Cppaapp': 'VR',
    'ABprpppppaa': 'VR',
    'Cppappa': 'VR',
    'Cppappp': 'VR',
    'Cpppppv': 'VR',

    'MSppaaap': 'DR',
    'MSppappp': 'DR',
    'MSpppppa': 'DR',
    'MSppappa': 'DR',
    'MSpppppp': 'DR',
    'MSppppap': 'DR',
    'Dpppaa': 'DR',
    'Dpaap': 'DR',
    'Dpppap': 'DR',
    'Dppap': 'DR',
    'Dppppa': 'DR',
    'Cpppaaa': 'DR',
    'Dppppp': 'DR',
    'Cppapaa': 'DR',
    'Cpppaap': 'DR',
    'Cppapap': 'DR',
    'Cppppaa': 'DR',
    'Cpppapa': 'DR',
    'Cppppap': 'DR',
    'Cpppppd': 'DR',
    'Cpppapp': 'DR',
}

individual_neuron = {
    'ABplapaaaapp': 'Ring interneuron',
    'ABprapaaaapp': 'Ring interneuron',
    'ABplapaaaapa': 'Anterior deirid, sensory neuron',
    'ABprapaaaapa': 'Anterior deirid, sensory neuron',
    'ABalpppppaa': 'Amphid neuron',
    'ABpraaappaa': 'Amphid neuron',
    'ABalppppaad': 'Amphid neuron',
    'ABpraaapaad': 'Amphid neuron',
    'ABalpppapav': 'Amphid finger cell',
    'ABpraaaapav': 'Amphid finger cell',
    'ABplppaappa': 'Amphid interneuron',
    'ABprppaappa': 'Amphid interneuron',
    'ABplaapappa': 'Amphid interneuron',
    'ABpraapappa': 'Amphid interneuron',
    'ABplpaapppa': 'Ring interneuron',
    'ABprpaapppa': 'Ring interneuron',
    'ABalaaaalal': 'Ring interneuron',
    'ABalaapaaar': 'Ring interneuron',
    'ABplpapaaap': 'Amphid interneuron',
    'ABprpapaaap': 'Amphid interneuron',
    'ABplapaaapav': 'Amphid interneuron',
    'ABprapaaapav': 'Amphid interneuron',
    'ABalapppaaa': 'Neuron, sends processes laterally and along dorsal cord',
    'ABarppaappa': 'Anterior lateral microtubule cell',
    'ABarpppappa': 'Anterior lateral microtubule cell',
    'ABplapappppap': 'Neuron associated with ALM',
    'ABprapappppap': 'Neuron associated with ALM',

    'ABalppppppaa': 'Amphid neurons',
    'ABpraaapppaa': 'Amphid neurons',
    'ABplaapapap': 'Amphid neurons',
    'ABpraapapap': 'Amphid neurons',
    'ABplpaappaa': 'Amphid neurons',
    'ABprpaappaa': 'Amphid neurons',
    'ABplaapapppa': 'Amphid neurons',
    'ABpraapapppa': 'Amphid neurons',
    'ABalpppppppa': 'Amphid neurons',
    'ABpraaappppa': 'Amphid neurons',
    'ABalpppapppa': 'Amphid neurons',
    'ABpraaaapppa': 'Amphid neurons',
    'ABalpppppppp': 'Neuron',
    'ABpraaappppp': 'Neuron',
    'ABalppaaapa': 'Ventral cord interneuron',
    'ABalaappapa': 'Ventral cord interneuron',
    'ABplpaapaap': 'Ventral cord interneuron',
    'ABprpaapaap': 'Ventral cord interneuron',
    'ABalaaapalr': 'Ventral cord interneuron',
    'ABalaaapprl': 'Ventral cord interneuron',
    'ABalpppaaaa': 'Ventral cord interneuron',
    'ABpraaaaaaa': 'Ventral cord interneuron',

    'ABprpapppap': 'Ventral cord interneuron',
    'ABalapaaaaa': 'Neuron',
    'ABalappapaa': 'Neuron',
    'ABalapapppa': 'Neuron',
    'ABalapppppa': 'Neuron',
    'ABplpapapap': 'Ring and ventral cord interneuron',
    'ABprpapapap': 'Ring and ventral cord interneuron',
    'ABprpappaap': 'Ring and ventral cord interneuron',
    'ABplaapapaa': 'Amphid wing cells',
    'ABpraapapaa': 'Amphid wing cells',
    'ABalpppppap': 'Amphid wing cells',
    'ABpraaappap': 'Amphid wing cells',
    'ABplpaaaaap': 'Amphid wing cells',
    'ABprpaaaaap': 'Amphid wing cells',
    'ABalppappap': 'Neuron',
    'ABarappppap': 'Neuron',
    'ABarppaappp': 'Neuron',
    'ABarpppappp': 'Neuron',

    'ABalapaaapa': 'Process runs along excretory canal',
    'ABalappappa': 'Process runs along excretory canal',
    'ABplaaaaaap': 'Male specific cephalic neurons',
    'ABarpapaaap': 'Male specific cephalic neurons',
    'ABplpaapapp': 'Male specific cephalic neurons',
    'ABprpaapapp': 'Male specific cephalic neurons',
    'ABplaaaaappa': 'Cephalic neurons',
    'ABarpapaappa': 'Cephalic neurons',
    'ABplpaappppa': 'Cephalic neurons',
    'ABprpaappppa': 'Cephalic neurons',

    'ABprppapaap': 'Ventral cord motor neurons',
    'ABplppapapa': 'Ventral cord motor neurons',
    'ABprppapapa': 'Ventral cord motor neurons',
    'ABplppapapp': 'Ventral cord motor neurons',
    'ABprppapapp': 'Ventral cord motor neurons',
    'ABplpppaaap': 'Ventral cord motor neurons',
    'ABprpppaaap': 'Ventral cord motor neurons',
    'ABprpapappp': 'Ventral cord motor neurons',
    'ABplpppaaaa': 'Ventral cord motor neurons',
    'ABplpaaaapp': 'Ventral cord motor neurons',
    'ABarappappa': 'Ventral cord motor neurons',
    'ABprpaaaapp': 'Ventral cord motor neurons',
    'ABprpappapp': 'Ventral cord motor neurons',
    'ABplpapappp': 'Ventral cord motor neurons',
    'ABplppaappp': 'Ventral cord motor neurons',
    'ABprppaappp': 'Ventral cord motor neurons',
    'ABplppappap': 'Ventral cord motor neurons',
    'ABprppappap': 'Ventral cord motor neurons',
    'ABplppapppa': 'Ventral cord motor neurons',
    'ABprppapppa': 'Ventral cord motor neurons',
    'ABplppapppp': 'Ventral cord motor neurons',
    'ABprppapppp': 'Ventral cord motor neurons',
    'ABprppppapp': 'Ring interneurons',

    'Caapaa': 'Ring interneurons',

    'ABplapaaapad': 'Neuron',
    'ABprapaaapad': 'Neuron',

    'ABalpapppaa': 'Pharyngeal interneuron',
    'ABarapappaa': 'Pharyngeal interneuron',
    'ABalpappaapa': 'Pharyngeal interneuron',
    'ABarapapaapa': 'Pharyngeal interneuron',
    'MSaaaaapaa': 'Pharyngeal interneuron',
    'MSaaaapaa': 'Pharyngeal interneuron',
    'ABarapapapp': 'Pharyngeal interneuron',
    'MSpaaapaa': 'Pharyngeal interneuron',
    'ABalapappaaa': 'labial neuron',
    'ABalappppaaa': 'labial neuron',
    'ABalapaappaa': 'labial neuron',
    'ABalaappppaa': 'labial neuron',
    'ABalppapppaa': 'labial neuron',
    'ABarapppppaa': 'labial neuron',
    'ABalapappap': 'labial neuron',
    'ABalappppap': 'labial neuron',
    'ABalapaappp': 'labial neuron',
    'ABalaappppp': 'labial neuron',
    'ABalppapppp': 'labial neuron',
    'ABarapppppp': 'labial neuron',
    'ABplpppaapap': 'Interneuron',
    'ABprpppaapap': 'Interneuron',
    'MSpaapaaa': 'Pharyngeal motorneuron',
    'ABaraapappa': 'Pharyngeal motorneurons',
    'ABaraappppa': 'Pharyngeal motorneurons',
    'ABaraapappp': 'Pharyngeal motorneuron',
    'ABaraappppp': 'Pharyngeal motorneuron',
    'MSpaaaaaa': 'Pharyngeal motorneuron',
    'MSpaaapap': 'Pharyngeal motorneuron',
    'ABalpaaappp': 'Pharyngeal neurons',
    'ABarapaappp': 'Pharyngeal neurons',
    'ABaraappaaa': 'Pharyngeal motorneuron',
    'ABaraapapaav': 'Pharyngeal motorneuron',
    'ABaraapppaav': 'Pharyngeal motorneuron',
    'ABalppppapaa': 'labial neurons',
    'ABpraaapapaa': 'labial neurons',
    'ABalapapapaa': 'labial neurons',
    'ABalapppapaa': 'labial neurons',
    'ABplpaaappaa': 'labial neurons',
    'ABprpaaappaa': 'labial neurons',
    'ABprpppaaaa': 'Motor neuron',

    'ABplpppaapp': 'Phasmid neurons',
    'ABprpppaapp': 'Phasmid neurons',
    'ABplapppappp': 'Phasmid neurons',
    'ABprapppappp': 'Phasmid neurons',

    'ABplapappppaa': 'microtubule cells',
    'ABprapappppaa': 'microtubule cells',

    'ABplpppaapaa': 'Ventral cord interneuron',
    'ABprpppaapaa': 'Ventral cord interneuron',

    'ABplapppaaa': 'Interneuron',
    'ABprapppaaa': 'Interneuron',
    'Caappa': 'Interneuron',
    'ABplpappppa': 'Interneuron',

    'ABalapaapaa': 'Ring interneuron',
    'ABalaapppaa': 'Ring interneuron',
    'ABplpaappap': 'Ring interneuron',
    'ABprpaappap': 'Ring interneuron',
    'ABplppaaaapp': 'Ring interneuron',
    'ABprppaaaapp': 'Ring interneuron',
    'ABalappaapa': 'Ring interneuron',
    'ABplppapaaap': 'Ring interneuron',
    'ABprppapaaap': 'Ring interneuron',
    'ABplppappaa': 'Ring interneuron',
    'ABprppappaa': 'Ring interneuron',
    'ABprpappaaa': 'Ring interneuron',
    'ABplppaapap': 'Ring motor neuron',
    'ABprppaapap': 'Ring motor neuron',
    'ABalpapaaaa': 'Ring interneuron',
    'ABarappaaaa': 'Ring interneuron',
    'ABprpapppaa': 'Ring interneuron',
    'ABprpappapa': 'Ring interneuron',
    'ABplpaapaaa': 'Ring interneuron',
    'ABprpaapaaa': 'Ring interneuron',
    'ABalpapapaa': 'Ring motor neuron',
    'ABarappapaa': 'Ring motor neuron',
    'ABalpppapad': 'Ring motor neuron',
    'ABpraaaapad': 'Ring motor neuron',
    'ABalppapaaa': 'Ring motor neuron',
    'ABarapppaaa': 'Ring motor neuron',
    'ABalapppaap': 'Ring motor neuron',
    'ABalaaaarlp': 'Ring motor neuron',
    'ABalaaaarrp': 'Ring motor neuron',
    'ABplpappaaa': 'Ring motor neuron',

    'ABplapaaapp': 'Ring interneuron',
    'ABprapaaapp': 'Ring interneuron',

    'ABalppapapa': 'Ring interneuron',
    'ABarapppapa': 'Ring interneuron',
    'ABplpaaaaaa': 'Ring interneuron',
    'ABprpaaaaaa': 'Ring interneuron',
    'ABplppapaap': 'Ring interneuron',
    'ABplppapaaaa': 'Ring interneuron',
    'ABprppapaaaa': 'Ring interneuron',

    'ABplpapaapa': 'Neuron',
    'ABprpapaapa': 'Neuron',
    'ABplpapappa': 'Neuron',
    'ABprpapappa': 'Neuron',
    'ABplppaaaaa': 'Neuron',
    'ABprppaaaaa': 'Neuron',
    'ABplpapaapp': 'Neuron',
    'ABprpapaapp': 'Neuron',
    'ABalpapapapp': 'Ring motor neuron',
    'ABarappapapp': 'Ring motor neuron',
    'ABalpapappp': 'Ring motor neuron',
    'ABarappappp': 'Ring motor neuron',
    'ABplpapaaaa': 'Ring motor neuron',
    'ABprpapaaaa': 'Ring motor neuron',
    'ABalppappaa': 'Ring motor neuron',
    'ABarappppaa': 'Ring motor neuron',

    'ABplaaaaaaa': 'Ring motor neuron',
    'ABarpapaaaa': 'Ring motor neuron',
    'ABplpaaapaa': 'Ring motor neuron',
    'ABprpaaapaa': 'Ring motor neuron',
    'ABplaapaapa': 'Neuron',
    'ABpraapaapa': 'Neuron',
    'ABplaaaaappp': 'Ring interneuron',
    'ABarpapaappp': 'Ring interneuron',
    'ABalapapapp': 'Neuron',
    'ABalapppapp': 'Neuron',
    'ABplpaaappp': 'Neuron',
    'ABprpaaappp': 'Neuron',

}

pharynx={

}